### PR TITLE
Feature redirection to the lobby

### PR DESCRIPTION
**Pull request by apple00juice**
Implemented the redirection to the lobbies when clicking them on the lobby list #38.
Additionally removed div's around tr's (lobbyitems) as they produced an error in the browser.

### CODE REVIEW

**Review by luis-tm — COMMENTED** [review]
Why are we calling create lobby in PublicLobbies? Dont we have to join an already created lobby?

**Comment by apple00juice** [comment]
> Why are we calling create lobby in PublicLobbies? Dont we have to join an already created lobby?

Where? If I do it is a mistake

**Comment by luis-tm** [comment]
> > Why are we calling create lobby in PublicLobbies? Dont we have to join an already created lobby?
> 
> Where? If I do it is a mistake

There is not actual call, but there is this comment:

// here we mocked the answer of the API create lobby

and a mocked response of the service.

**Comment by apple00juice** [comment]
> > > Why are we calling create lobby in PublicLobbies? Dont we have to join an already created lobby?
> > 
> > 
> > Where? If I do it is a mistake
> 
> There is not actual call, but there is this comment:
> 
> // here we mocked the answer of the API create lobby
> 
> and a mocked response of the service.

Yea, that should be "...API join lobby", happened because I used your method for creating the lobby as a template.
Changed it

**Review by luis-tm — APPROVED** [review]
Ah sorry! I got confused by the comment then :D

**Review by mkorob — APPROVED** [review]

**Comment by apple00juice** [comment]
close #38

**Pull request merged**
