### PR TITLE
winner windows

### PR DESCRIPTION
**Pull request by luis-tm**
Show "winner window" when receiving gameOver event from the server.

Victory:

image

Defeat:

image

(This pull request will not be merged until a server error related to the sending of the gameOver event is fixed)

### CODE REVIEW

**Comment by luis-tm** [comment]
Most of the "changes" are just because of the autoformat... The changes are the new functions in game.js, map.js and the confetti.

**Comment by luis-tm** [comment]
progresses #62 #109

**Review by mkorob — APPROVED** [review]
Looks great, the confetti is cool! :D

**Review by apple00juice — APPROVED** [review]
Perfect 👍 I really love the confetti 🎊

**Pull request merged**
