### PR TITLE
Info page

### PR DESCRIPTION
**Pull request by luis-tm**
New information game view.

For changes related to content, you can change whatever you want directly in the .js :)

### CODE REVIEW

**Comment by luis-tm** [comment]
image
image
image
image
image
image

**Review by paolovic — APPROVED** [review]

**Comment by paolovic** [comment]
👌🏻👌🏻👌🏻

**Review by apple00juice — APPROVED** [review]
That is really good! tyvm
I am not really sure as grammar and stuff is not my strong suit but I quickly threw it into prowritingaid

"By clicking on one of the tiles within the movement range, a pop-up window will appear allowing the player to move the unit to the chosen location."
Missing comma: "a pop-up window will appear, allowing the player"

"If an enemy is in range when selecting a unit, the tiles where the enemys are will highlighted in red."
=> it will highlight the tiles where the **enemies** are standing in red

I am not really sure bet those two sound a bit weird, but could also be me

"A window will appear showing the result of each player of the game."
Shouldn't it be:
"A window will appear showing the result of the game of each player."

And right after:
"From this window will be possible to see statistics of the game, to play again, or going back to the home page."
"From this window **it is** possible to see statistics of the game, to play again, or **go** back to the home page."

**Comment by paolovic** [comment]
must have been a lot of work! thank you!!!

**Comment by luis-tm** [comment]
> That is really good! tyvm I am not really sure as grammar and stuff is not my strong suit but I quickly threw it into prowritingaid
> 
> "By clicking on one of the tiles within the movement range, a pop-up window will appear allowing the player to move the unit to the chosen location." Missing comma: "a pop-up window will appear, allowing the player"
> 
> "If an enemy is in range when selecting a unit, the tiles where the enemys are will highlighted in red." => it will highlight the tiles where the **enemies** are standing in red
> 
> I am not really sure but those two sound a bit weird, but could also be me
> 
> "A window will appear showing the result of each player of the game." Shouldn't it be: "A window will appear showing the result of the game of each player."
> 
> And right after: "From this window will be possible to see statistics of the game, to play again, or going back to the home page." "From this window **it is** possible to see statistics of the game, to play again, or **go** back to the home page."

"enemys" :O ... 

changed! ty for checking!!! :)

**Pull request merged**
