### PR TITLE
"Created the view of the lobby which constist of a Game view, a Map c…

### PR DESCRIPTION
**Pull request by apple00juice**
…omponent and Tile components." #45

### CODE REVIEW

**Review by mkorob — APPROVED** [review]
It's a bit difficult to leave useful feedback without seeing the implemented changes given the big visual element, will check it out after pulling, but seems like it will loook cool!!

**Comment by apple00juice** [comment]
> It's a bit difficult to leave useful feedback without seeing the implemented changes given the big visual element, will check it out after pulling, but seems like it will loook cool!!

True, I probably should have added some pictures...
image

**Comment by apple00juice** [comment]
> It's a bit difficult to leave useful feedback without seeing the implemented changes given the big visual element, will check it out after pulling, but seems like it will loook cool!!

Yea, idk why github has to show every png ^^

**Review by luis-tm — COMMENTED** [review]
It's great!!! good job :)

Only one thing: Is it necessary to include the game in the router with an id, as in lobbies? In principle, we could have more than one game at the same time.

**Comment by apple00juice** [comment]
> It's great!!! good job :)
> 
> Only one thing: Is it necessary to include the game in the router with an id, as in lobbies? In principle, we could have more than one game at the same time.

Ah yea, I will change that. Somehow I forgot that ^^

**Review by luis-tm — APPROVED** [review]

**Pull request merged**
