### PR TITLE
Map view add units

### PR DESCRIPTION
**Pull request by apple00juice**
Created the sprite sheets  for the units (attack animations missing), and implemented that they are displayed correctly.

### CODE REVIEW

**Review by mkorob — APPROVED** [review]
Units look super cool and the possible error alerts to the client are very detailed! :)

**Review by luis-tm — APPROVED** [review]
Wow! Great job :) You deserve a whole brownie cake.

**Review by paolovic — APPROVED** [review]
Sheeesh! Thank you very much!

**Comment by apple00juice** [comment]
ty for the review 😄

**Pull request merged**
